### ISSUE TITLE
Haftalık Toplantılar

### ISSUE THREAD

**Issue by ntgcyslyrt** [kcd/staj#1]
Çalışma No:2

Yer:Tuğçe'nin evi

Katılım: @kcd
              @sedadogan
              @tugceyesilyurt
              @bgmtpyldz

Tarih:30 Ekim 2012

Gündem:
1.İlişki şeması oluşturulması
2.Aylık raporlama
3.Aylık video ve poster çalışmaları-1

**Comment by seyyah** [comment]
Sonuçta neler oldu? Aylık raporlama vakti geliyor?

**Comment by begum** [comment]
Bugün yapacağımız toplantıdan sonra aylık raporu tamamlayıp, wiki bölümünde yayımlarım hocam.

**Comment by seyyah** [comment]
https://github.com/kcd/staj/wiki/ekip dosyayı şekillendirin: kim hangi rolde?

**Comment by seyyah** [comment]
https://github.com/kcd/staj/wiki/plan dosyasını şekillendirin: dönemlik, aylık ve haftalık iş-zaman planınız nedir?

**Comment by kcd** [comment]
https://github.com/kcd/staj/wiki/ekip tamamlandı.
https://github.com/kcd/staj/wiki/plan tamamlandı.
1.İlişki şema taslağının oluşturulması (toplantıda görüşülecek). @kcd
2.Aylık raporlama için toplantı raporlarının değerlendirilmesi ve eleştiriler doğrultusunda proje gidişatına yön verilmesi. @bgmtpyldz 
3.Aylık poster taslağının lucidchart aracılığı ile hazırlanması. @ntgcyslyrt
   Aylık video çekiminin yapılması. @sedadogan

**Comment by ntgcyslyrt** [comment]
Aylık poster taslağı lucidchart ile tasarlandı.

**Comment by seyyah** [comment]
- Lucidchart ekran resmini buraya koyalım. Ardından ilgili iş kaydına #8 koyalım.
- Videonun youtube linkini buraya koyalım. Ardından ilgili iş kaydına #7 koyalım.

**Comment by ntgcyslyrt** [comment]
Staj poster taslak resmi buradadır,

 ![staj-poster](http://img593.imageshack.us/img593/5145/stajposter.png)

**Comment by sedadogan** [comment]
Staj taslak videosu verdiğim linkte bulunmaktadır.
http://www.youtube.com/watch?v=5w4VqRgaDg0&feature=youtu.be

**Comment by ntgcyslyrt** [comment]
aylık rapor hazırlandı. #5 görevi kapatıldı.
