### ISSUE TITLE
RailsGuides konularının blog girdisine dönüştürülmesi part-1

### ISSUE THREAD

**Issue by kcd** [kcd/staj#10]
##### RailsGuides konuları
- Getting Started with Rails konusu @ntgcyslyrt 
  -1 Guide Assumptions
  -2 What is Rails?
  -3 Creating a New Rails Project3 Creating a New Rails Project
- Layouts and Rendering in Rails @bgmtpyldz 
  -1 Overview: How the Pieces Fit Together
  -2 Creating Responses
  -3 Structuring Layouts
- Action Controller Overview @kcd
  -1 What Does a Controller Do?
  -2 Methods and Actions
  -3 Parameters
- Testing Rails Applications @sedadogan 
  -1 Why Write Tests for your Rails Applications?
  -2 Introduction to Testing
  -3 Unit Testing your Models

bu şekilde paylaşıldı, bloglarda ilk ayın çalışmalarına başlanacak.

**Comment by seyyah** [comment]
Notlarıma bakmadan hatırlayamadığımdan soruyorum. Bu iş bir ayda mı halledilecekti? Öyleyse bir şey yapmanız gerekmiyor. Yok eğer bu ay yapılacak olan part-1 ise başlık "RailsGuides konularının blog girdisine dönüştürülmesi - part1" biçiminde değiştirin.

**Comment by kcd** [comment]
Tamam hocam düzenliyorum şuan issues'leri.

**Comment by kcd** [comment]
Bu ay konuların ilk 3 alt başlığının bitirilmesi planlanıyor. İssue bu şekilde güncellendi.

**Comment by seyyah** [comment]
diğer partlar (part 2 ve part 3'e) ait iki adet iş kaydı oluştur ve `future` milestone'una ata.

**Comment by seyyah** [comment]
> @kcd: Bu ay konuların ilk 3 alt başlığının bitirilmesi planlanıyor. İssue bu şekilde güncellendi.

Milestone'u düzelttim. Sonra ki aylarda değil. Bu ay içerisinde yapacaksınız.

**Comment by kcd** [comment]
(ntgcyslyrt )
- Getting Started with Rails konusu 

blog girdileri-->

http://ntgcyslyrt.github.com/111/rails/

http://ntgcyslyrt.github.com/111/rails_projesi_olusturma/

(bgmtpyldz)
- Layouts and Rendering in Rails

blog girdileri --> 

http://bgmtpyldz.github.com/112/railsde-layouts-ve-rendering-part1/

http://bgmtpyldz.github.com/112/railsde-layouts-ve-rendering-part2/

(kcd)
- Action Controller Overview 

blog girdileri-->

http://kcd.github.com/112/mvc-mimarisi/

http://kcd.github.com/112/Ruby-on-Rails-Controller-1/

(sedadogan)
- Testing Rails Applications 

blog girdileri-->

http://sedadogan.github.com/111/Rails-Uygulamalarinda-Test-Part-1/

http://sedadogan.github.com/112/Testlerde-Kullanilan-Uygulamalar/

https://github.com/sedadogan/sedadogan.github.com/blob/master/1/_posts/2012-12-07-Testlerde-Kullanilan-Uygulamalar.md
