### ISSUE TITLE
Bildiri Özetinin Yazılması

### ISSUE THREAD

**Issue by kcd** [kcd/staj#11]
#### Özet:

Üniversitemiz bünyesinde staj işlemleri öğrenci işleri üzerinden; staj evrakı, sigorta belgesi, kimlik belgesi, değerlendirme formu vb. evraklar ile yürütülmektedir. Bu projenin amacı bu sistemi online platforma taşımaktır. Bu sayede staj komisyonu ve öğrenci iş yükü minimum seviyeye çekilecektir. Pilot bölge olarak 19 Mayıs Üniversitesi Mühendislik Fakültesi Bilgisayar Mühendisliği bölümü seçilecek, projenin kabul edilmesi halinde üniversitenin diğer bölümleri içinde sistem geliştirilecektir.Online staj sisteminde staj başvuruları ve staj kayıtları yapılabilecek ve staj defterlerinin pdf hali sisteme yüklenebilecektir.Ayrıca kurumlar stajyer ilanı verebilecektir. Sisteme öğrenci ve komisyon girişleri google posta hesaplarından otomatik olarak yapılabilecektir(ad.soyad@bil.omu.edu.tr). Proje geliştirme aşamasında işletim sistemi olarak GNU/Linux dağıtımlarından ubuntu tercih edildi. Framework olarak ROR(Ruby on Rails) tercih edildi. Kodlama aşamasında standartlar slim,less ve coffeescript olarak belirlendi. Test aracı olarak cucumber, arayüz çerçevesi olarak twitter bootstrap seçildi. Mockup çalışmaları lucidchart ve yuml ile yapılmaktadır. Bilgi paylaşımları da github ve trello üzerinden yürütülmektedir.
###### Proje Sorumluları:

KAMİLE CANAN DEMİREL
SEDA DOĞAN
NURDAN TUĞÇE YEŞİLYURT
AYŞE BEGÜM TOPYILDIZ
###### Proje Danışmanları:

YRD.DOÇ.DR. NURETTİN ŞENYER
DR. GÖKHAN KAYHAN
### Çalışma 1: SUBJE ELEKTRONİK BELGE YÖNETİM SİSTEMİ

Özel sektör, kamu kurum ve kuruluşlarının faaliyetleri sonucu ürettikleri çoğunlukla 
kağıt olmak üzere değişik ortamlarda üretilmiş belgelerin, elektronik belgelere 
dönüştürülmesi, üretilmesi, elektronik ortamda imzalanarak iletilmesi ve istenildiği 
taktirde esnek bulut bilişim (cloud computing) sunucularında saklanması. Ağırlıkla 
Java, gae, gwt, gdata, google storage, bigquery, pdfbox, itext teknolojileri 
kullanılmıştır. Sistem TS 13298 standartlarına uygun olarak hazırlanmıştır
Proje Sorumlusu: Emrah SARI
Proje Danışmanı: Dr. Sadık EŞMELİOĞLU
ÇANKAYA ÜNİVERSİTESİ
### Çalışma 2: SORU BANKASI

Bu projenin amacı ogretim gorevlilerinin istedigi alanda sorular ve sorulara ait 
şıklar girebilecegi ve ogrencilerin de bu soruları belirtilen sure icinde cozebilecegi 
sanal bir ortam olusturmaktır.Sisteme kayıtlı ogretmenler soruları konularına gore 
ekleyebilir ve ogrenci kaydı yapabilir.Sistemde kayıtlı ogrenciler sistemdeki 
sorulardan ister konu testi ister deneme sınavı olabilir
Proje Sorumlusu: Emrah SOYTEKİN
Proje Danışmanı: Yrd. Doç. Dr. Şahin EMRAH
ANKARA ÜNİVERSİTESİ
### Çalışma 3:ONLINE HASTANE

Online Hastane projesinin amacı, özellikle tıbbı olanakların az olduğu bölgelerde 
yaşayan insanların talep ettikleri hastanelerden kolaylıkla randevu alabilmelerini
sağlamaktır. Hastanın randevu aldıktan sonra hastaneye gitmeden, doğrudan hekim 
ile iletişim kurup hastaneye gelmesi gerekliliği üzerinde anlaşmaya varabilecekleri, 
muayeneye başlanabileceği veya başlanılan bir tedavinin takibinde kullanılacak bir 
platform sağlayarak hastaneye gelmesi çok kolay olmayan vatandaşlara destek 
olmak. Hekimlerin uzmanlık alanlarına göre verecekleri kritik kararlarda hekimlere 
yardımcı olması için “Machine learning” tekniği ile geliştirilmiş, hastalığı daha 
doğru kestirmek için kullanılacak bir uygulamayı web üzerinden sağlamaktır.Proje 
ile amaçlanan bütün hastanelerin ortak bir çatı altında toplanmasını sağlayıp, 
Türkiye'nin ücra bir köşesinde yaşayan bir bireyin dahi bu hizmetten sıkıntı 
çekmeden maksimum düzeyde faydalanmasını sağlamaktır. Bu amaçla bütün 
hastanelerin ortak kayıt olabileceği ve hasta, doktor, hastane arasındaki işlemlerin 
yürütülebileceği ortak bir platforma ihtiyaç vardır.
Proje Sorumluları: Muharrem ENGİN, Yakup BULUT
Proje Danışmanı: Dr. Sevil ŞEN
HACETTEPE ÜNİVERSİTESİ
Proje Sorumluları: Muharrem ENGİN, Yakup BULUT
Proje Danışmanı: Dr. Sevil ŞEN
HACETTEPE ÜNİVERSİTESİ
### Çalışma 4:ONLINE VETERİNER BİLGİ YÖNETİM SİSTEMİ

(ONLINE VETERINARY)
Sistem sayesinde veterinerler müşteri ve hayvan takibi yapabilir. Hayvan 
tedavilerini, rutin kontrollerini, ve diğer loglarını sisteme kaydedebilir ve internet 
aracılığı ile erişim sağlayabilir. Sistem bir web uygulamasıdır ve veterinerlerin 
yedek alma, veri kaybı gibi sıkıntılarını ortadan kaldırır. Ayrıca sistem aracılığı ile 
ilanlarını yayınlayabilir, takvimlerini ve iş planlarını düzenleyebilir.
Proje Sorumluları: Ali Kaan KİRİŞ, Onur BABAOĞLU,Enver Can KARADUMAN
Proje Danışmanı: Yrd. Doç. Dr. Erol ÖZÇELİK
ATILIM ÜNİVERSİTESİ
### Çalışma 5:DMS

TSE standartlarına uygun belge ve döküman yönetim sistemi. DMS projesini genel 
amacı içersinde bulunduğu kurumun hiyerarşik yapısını çıkarıp kullanıcıları 
belirlemek ve bu kullanıcılar veya kurumlar arasında TSE standartlarına uygun belge 
ve dökümanlar oluşturmak. Kullanıcılar arası haberleşmeyi sağlamaktır. Ana amaç 
gelen giden evrak takibini kolaylaştırmak. Hangi süreçte olduklarını takip 
edebilmektir.
Proje Sorumluları: Mesut ALTINYAPRAK, 
Proje Danışmanı: Yrd. Doç. Dr. Gökhan ŞENGÜL
ATILIM ÜNİVERSİTESİ
### Çalışma 6:ELEKTRONİK SENET ve ÇEK

Günümüzde internet ortamında çeşitli belgeler elektronik imza ile onaylanıp 
kullanılmaktadır. Günümüz piyasasında yaygın olarak kullanılan çek ve senedin 
elektronik ortamda dolaşımını sağlayacak bir yazılım alt yapısı geliştirmek projenin 
amacıdır
Proje Sorumlusu: Ahmet OKAY
Proje Danışmanı: Öğr. Gör. Kaya Han KILAN
BAŞKENT ÜNİVERSİTESİ
## Kaynak
- http://ankara.bps.org.tr/

**Comment by seyyah** [comment]
Özeti iş gövdesine yazıp, kapatalım.
