### ISSUE TITLE
Kaynak kitaplar

### ISSUE THREAD

**Issue by kcd** [kcd/staj#12]
## Yararlanılan Kaynak Kitaplar

<table>
<tr>
<td>JQuery</td>
<td><a href="http://tr.scribd.com/doc/113836954/jQuery"><img class="" alt="" src="http://i.imgur.com/myi0z.png" /></a></td>

<td>The Ruby Prog</td>
<td><a href="http://tr.scribd.com/doc/113838195/10-RubyProg"><img class="" alt="" src="http://i.imgur.com/9pAdD.png" /></a>

<td>Rails in action</td>
<td><a href="http://tr.scribd.com/doc/113837789/18-Rails-in-Action"><img class="" alt="" src="http://i.imgur.com/jqdbA.png" /></a></td>
</tr>

<tr>
<td>Security on Rails</td>
<td><a href="http://tr.scribd.com/doc/113838724/15-Security-on-Rails-2009-Pragmatic-Bookshelf-Publishing"><img class="" alt="" src="http://i.imgur.com/bRfOH.png" /></a></td>

<td>Rails Test Prescriptions</td> 
<td><a href="http://tr.scribd.com/doc/113839209/50-Rails-Test-Prescriptions"><img class="" alt="" src="http://i.imgur.com/wGRXt.png" /></a></td>

<td>Continuous Testing</td>
<td><a href="http://tr.scribd.com/doc/113839404/53-Continuous-Testing-With-Ruby-Rails-Javasript-2011-Pragmatic-Bookshelf-Publishing"><img class="" alt="" src="http://i.imgur.com/lFftG.png" /></a></td>
</tr>

<tr>
<td>Coffee Script</td>                
<td><a href="http://tr.scribd.com/doc/113836325/Coffeescript-Slides"><img class="" alt="" src="http://i.imgur.com/FMSxZ.png" /></a></td>  

<td>Smooth Coffee Script</td>
<td><a href="http://tr.scribd.com/doc/113841421/Smooth-CoffeeScript-Web-Optimized"><img class="" alt="" src="http://i.imgur.com/f2KHt.png" /></a></td>

<td>Slim</td>
<td><a href="http://tr.scribd.com/doc/113841273/Rdoc-info-Slim-1"><img class="" alt="" src="http://i.imgur.com/FR892.png" /></a></td>
</tr>

<tr>
<td>Sass</td>
<td><a href="http://tr.scribd.com/doc/113841369/Sass"><img class="" alt="" src="http://i.imgur.com/n1zdE.png" /></a></td>
</tr>
</table>

**Comment by sedadogan** [comment]
Eksik olan kaynak kitaplar bulundu ve grup üyeleriyle paylaşıldı.

**Comment by seyyah** [comment]
Yarın yanınızda getirin.

**Comment by sedadogan** [comment]
Peki hocam.

**Comment by seyyah** [comment]
Kitap listesini iş gövdesine resimleriyle destekleyerek yazın

**Comment by seyyah** [comment]
kapatabiliriz. Ellerine sağlık, tam da istediğim gibi olmuş :+1:

**Comment by sedadogan** [comment]
Hocam bazı kitaplar eksik oldu, onlar da telif haklarından dolayı galiba yüklenmedi :S Teşekkür ederim hocam.

**Comment by seyyah** [comment]
iş gövdesini tekrardan düzenledim. Gözden kaçmasın.
