### ISSUE TITLE
Toplantı-6

### ISSUE THREAD

**Issue by begum** [kcd/staj#13]
wiki'de toplantı 6'nın raporu yazılacak.

**Comment by begum** [comment]
https://github.com/kcd/staj/wiki/toplanti6 hazırlandı.

**Comment by seyyah** [comment]
bu tamamsa kapatabilirsiniz.

**Comment by begum** [comment]
evet, düzenleme yaptıktan sonra kapatmayı unutmuşum. tamamlandı.

**Comment by seyyah** [comment]
böylelikle `next (alaçam)` işleri bitti. Milestone'da şunları yapıyoruz.
1. next (alaçam) -> alaçam
2. future (asarcık) -> next (asarcık)
3. future (bafra)

bunu bir kereliğine ben yaparım.
