### ISSUE TITLE
Ç1-Blog oluşturulmasının açıklanması ve kendi blogunda bunun yayınlanması

### ISSUE THREAD

**Issue by sedadogan** [kcd/staj#18]
@bsaral

**Comment by seyyah** [comment]
bu olmamış. Kişileri colloborate edin, ondan sonra da assign.

**Comment by kcd** [comment]
2012/11/14 nurettin senyer notifications@github.com

**Comment by seyyah** [comment]
colloborate edelim, olmazsa çıkarırız.

**Comment by seyyah** [comment]
> Please stop Cc-ing me.

sebebini çözdünüz mü? `@betülsaral` yaklaşık olarak `@bet`ülsaral ediyor :( ve böyle birisi mevcut. Kişiye kısa bir özür mesajı atalım.

> I am sory CC-ing you.

gibi.

**Comment by sedadogan** [comment]
çözdüm hocam düzelttim.

14 Kasým 2012 21:39 tarihinde nurettin senyer notifications@github.comyazdý:

**Comment by kcd** [comment]
14 Kasým 2012 21:36 tarihinde nurettin senyer notifications@github.comyazdý:

**Comment by bsaral** [comment]
Bu görev tamamlandı.Yalnız şu an github da bir problem var galiba blogumda makalemin sadece bir kısmı gözüküyor.Yakın zaman da gerisi gelir diye ümit ediyorum.Önizlemesine şurdan bakabilirsiniz.

https://github.com/bsaral/bsaral.github.com/blob/master/1/_posts/14-11-2012-blog.md

**Comment by seyyah** [comment]
@bsaral böyle birisi işte. Tebrikler ;)

**Comment by bsaral** [comment]
teşekkür ederim hocam :)

**Comment by bsaral** [comment]
http://bsaral.github.com/111/blog/

**Comment by ntgcyslyrt** [comment]
ellerine sağlık @bsaral :)

**Comment by kcd** [comment]
@bsaral  emeğine sağlık :) görevimiz başarıyla tamamlandığına göre kapatıyorum :)
