### ISSUE TITLE
Ç1-Taslak video hazırlama

### ISSUE THREAD

**Issue by sedadogan** [kcd/staj#19]
[![](http://www.amisosyazilim.com/wp-content/uploads/2012/11/Thumbnail2.jpg)](http://www.youtube.com/watch?v=PlyMn4fPstw&feature=plcp)

**Comment by kcd** [comment]
geliştirilen video linki-> http://www.youtube.com/watch?v=PlyMn4fPstw&feature=plcp

**Comment by seyyah** [comment]
@mehmetmertyildiran resim önizlemeli tıklandığında youtube'a gidecek biçimde iş gövdesini güncelle

@kcd bir kereliğine bu noktada yardımcı olun

**Comment by kcd** [comment]
peki hocam ben düzenleyim örnek olsun arkadaşa , işi tekrar kapatıyorum di mi?

**Comment by seyyah** [comment]
kapatma yetkisi sen de. Son kontrolleri yapıp, tekrardan açabilirsin.

**Comment by kcd** [comment]
hocam bu tek seferlik bir işti aylık video için issues vardı, düzelttim kapatıyorum işi.

**Comment by seyyah** [comment]
@kcd,

``` markdown
# BAD
![](http://www.amisosyazilim.com/wp-content/uploads/2012/11/Thumbnail2.jpg)
 http://www.youtube.com/watch?v=PlyMn4fPstw&feature=plcp

# GOOD
[![](http://www.amisosyazilim.com/wp-content/uploads/2012/11/Thumbnail2.jpg)](http://www.youtube.com/watch?v=PlyMn4fPstw&feature=plcp)
```

Are you ok?

**Comment by seyyah** [comment]
düzelttim
