### ISSUE TITLE
İlişki şeması mockupları

### ISSUE THREAD

**Issue by begum** [kcd/staj#2]
Yuml kullanılarak ilişki şemasının oluşturulması @kcd

**Comment by kcd** [comment]
http://yuml.me/aaab9c8b
İlişki şemasının şuan ki taslağı çizildi, staj tercih kısmı iyileştirilecek.

**Comment by seyyah** [comment]
@kcd bunları şöyle yapalım,

``` markdown
# WRONG
http://yuml.me/aaab9c8b

# CORRECT
[![](http://yuml.me/aaab9c8b.jpg)](http://yuml.me/edit/aaab9c8b)
```

Bu durumda şöyle görünecek,

[![](http://yuml.me/aaab9c8b.jpg)](http://yuml.me/edit/aaab9c8b)

Ayrıca görünümde de "Scruffy" yerine "Plain" yaparsak (ki siz de böyle yapacaksınız),

[![](http://yuml.me/9f43dc97.jpg)](http://yuml.me/edit/9f43dc97)

Bu çizimlerin olgunlaştırılması gerekiyor: `has-a`, `is-a`, `1-1`, `1-N`, `1..*-1..*`. Bunları sonra konuşuruz. Gündeminize alın.

**Comment by kcd** [comment]
trelloda ilgili card'a taşındı.
