### ISSUE TITLE
Ç1-Heroku inceleme, deploy hatasını araştırma

### ISSUE THREAD

**Issue by sedadogan** [kcd/staj#20]
@aydintd

**Comment by ghost** [comment]
kcd/staj deposunu clone layip, heroku' da bi hesap açıp oraya git komutlarıyla yerleştirmeye çalıştım. Deploy esnasında bi problem gözlemlemedim. 

Ama proje açılmıyordu. 500 Hatası veriyor(Bir şeyler ters gitti gibi bir hata.) Rails kodlarında neyin hangi işe yaradığını pek bilmediğimden sorunun nereden kaynaklandığını çözemedim.

Olay belki gemfile'dadır diye bir bundle install yaptığımda :

An error occurred while installing mysql2 (0.3.11), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.11'` succeeds before bundling

hatasını aldım. Gemfile'da ilgili gem'i kaldırdığımda bundle düzgün kuruyor gemleri.
(roktas bir defasında heroku'nun veritabanı içeren web uygulamalarında sıkıntı çıkarttığını söylemişti.)

Aşağıda da belirttiğim railsapps.github.com 'da heroku için veritabanında postgresql ile ilgili bir kaç kurulumdan bahsetmiş (neden mysql değil diye aklıma takılmadı değil, buna sonra bakacağım.)

Gemfile'daki değişiklikleri commit edip tekrar heroku'ya push ettiğimde bu sefer aynı hatayı almadım.
Sayfayı bir süre açmaya çalıştıktan sonra şöyle diyor : (örnek olarak oluşturduğum heroku sayfasının linkini veriyorum : )

http://shielded-chamber-7735.herokuapp.com/

Dediğim gibi rails kodlarından pek anlamadığımdan neden böyle bir şey diyor hala emin değilim. Ama index'lere baktığımda slim formatını görüyorum. Belki bu yüzden de heroku uygulamayı açamıyor olabilir. 

Şimdilik bu kadar, ilerleme kaydedersem eğer issue olarak gireceğim.

Yararlandığım kaynaklarsa şöyle :

https://devcenter.heroku.com/articles/git
http://railsapps.github.com/rails-heroku-tutorial.html

**Comment by seyyah** [comment]
daha önceden gruba yazdığım `heroku log` çıktısını buraya yaz

**Comment by ghost** [comment]
heroku'nun ışığıyla aydınlandım [1] ;)

seyyah@ror:~$ git checkout ch03
[...]
seyyah@ror:~$ heroku create rails3ch03 --stack cedar --remote heroku03
[...]
seyyah@ror:~$ git push heroku03 ch03:master
[...]
seyyah@ror:~$ heroku run rake db:migrate --app rails3ch03

bu komutların ayrıntıları mail zincirinde verilmiş,

$ rake db:drop | create | seed
$ heroku logs --app rails3ch03
$ heroku logs -t
$ heroku run rake db:migrate --app rails3ch03
$ heroku run:detached rake db:migrate --app rails3ch03
$ sudo gem install taps # yüklü değilse
$ heroku db:pull --app rails3ch03 --confirm rails3ch03

**Comment by ghost** [comment]
Merhaba tekrar,

@seyyah hocam öncelikle yukarıdaki mailinizde söylediğiniz komutların çıktısını alamadım.
Anlayamadım daha doğrusu tam olarak ne yapmak istediğimizi bu yüzden bi kenara bırakmak zorunda kaldım
devam edemiyordum çünkü.

heroku üzerinde siteyi çalıştıramıyorum hala. bunun sebeplerini araştırdım biraz. Heroku mysql desteklemediğini gördüm. Sıkıntının buradan olabileceğini varsayarak bi kaç araştırma yaparak Gemfile'dan

``` ruby
gem 'mysql2'  
```

yerine şöyle bi kod parçası koydum :

``` ruby
group :development do
  gem 'sqlite3', '~> 1.3.5'
  gem 'rspec-rails', '~> 2.6.1'
end

group :production do
  gem 'pg', '~> 0.12.2'
end
```

Burada diyorsun ki `development` ortamında sqlite3 db'yi, deploy/production'da ise pg'yi kullan diyorsun.

bir de ayrıyetten heroku'nun kendi gem'inin eksik olduğunu görüp onuda ekledim.

``` ruby
gem 'heroku'
```

bundle-install yaptığımda hata verdi, local'de de postgresql kurulumunu yapmam gerektiğini söyledi.
onu da biraz "istemeyerek" kurdum. Daha sonrasında sorun çıkartmadı bundle.

Daha sonra değiştirdiğim ayarları database.yml içersinde tekrar tanımladım. (mysql2 yerine sqlite3)

Sonrasında bunu rails server diyerek localhost da denemek istedim. ama olmadı. Çıkan hatayı araştırdığımda
app altındaki view'in çalışması için rails de controller komutunu çalıştırmam gerektiğini öğrendim ve çalıştırdım şöyle :

``` bash
$ rails g controller home index
```

lakin .html.slim dosyalarının bir şekilde üzerine yazmak istiyor. Bunu yapmasına izin vermedim hayır diyerek.

Sonrasında localhost da çalıştırdım ve sonunda siteyi görüntüledim.

Herokuya deploy ettiğimde de görüntülemeyi başardım. 

Buradan bakabilirsiniz :  http://shielded-chamber-7735.herokuapp.com/

Sanırım oldu :)

**Comment by seyyah** [comment]
Süpersin ;)

**Comment by kcd** [comment]
https://staj.herokuapp.com deploy ettim sonuç aynı güzellikte :) ellerine sağlık Aydın..
![](http://i.imgur.com/q7a8N.png)

**Comment by seyyah** [comment]
@kcd sorun çözüldüyse bunu kapat

**Comment by kcd** [comment]
evet hocam çözüldü kapatıyorum.
