### ISSUE TITLE
Ç1-Bootstrap temel araştırma

### ISSUE THREAD

**Issue by kcd** [kcd/staj#21]
- Blog Girdisi: http://tugdev.github.com/111/BOOTSTRAP/
- Demo: http://tugdev.github.com/bootstrap/
- Kodlar: https://github.com/tugdev/bootstrap/tree/gh-pages

**Comment by tugdev** [comment]
bootstrap araştırma sonucu  http://tugdev.github.com/111/BOOTSTRAP/

depoda örnek kodların oluşturulması  demo http://tugdev.github.com/bootstrap/
ve kodları https://github.com/tugdev/bootstrap/tree/gh-pages

**Comment by seyyah** [comment]
@tugdev 
1. [üstte ki](https://github.com/kcd/staj/issues/21#issuecomment-10481347) kommentin içeriğini iş gövdesine koy
2. iş gövdesinde blog'unun ekran görüntüsünü ver

**Comment by seyyah** [comment]
bunu senin yerine bir kereliğine yapıyorum
