### ISSUE TITLE
User modelinin oluşturulması

### ISSUE THREAD

**Issue by ntgcyslyrt** [kcd/staj#23]
Sisteme login olarak girebilecek  user modelini oluşturmak için;

```
 $ rails g model user 
```

komutunu verdik. Bu komutu verdikten sonra rails uygulaması otomatik olarak modelimizi, migrate dosyamızı ve test dosyalarını oluşturacaktır. 

```
$ ls -al app/models/

toplam 12
drwxrwxr-x 2 nty nty 4096 Kas 18 00:10 .
drwxrwxr-x 8 nty nty 4096 Kas 17 19:22 ..
-rw-rw-r-- 1 nty nty    0 Kas 17 19:22 .gitkeep
-rw-rw-r-- 1 nty nty  467 Kas 18 18:27 user.rb
```

```
$ ls -al db/migrate/

toplam 16
drwxrwxr-x 2 nty nty 4096 Kas 18 18:27 .
drwxrwxr-x 3 nty nty 4096 Kas 18 19:14 ..
-rw-rw-r-- 1 nty nty 1472 Kas 18 00:12 20121117214953_create_users.rb
-rw-rw-r-- 1 nty nty 1837 Kas 18 18:27 20121118162749_add_devise_to_users.rb
```

Daha sonra db/seeds.rb içine kontrolü sağlamak için;

User.create(email:"staj@staj.com", password:"123456", password_confirmation:"123456")
User.create(email:"staj@staaj.com", password:"123456", password_confirmation:"123456")

verileri girildi.

**Comment by seyyah** [comment]
@kcd bunun için ayrı bir işe gerek yoktu! Var olan #22 nolu işin alt parçasıydı. Bunun kararı ise Trello'da ki card'dan gelir. Trello'da ki bir kartın GH:Issues'da bir **yalnız** bir karşılığı olmalıdır.

**Comment by kcd** [comment]
hocam siz bunların hepsi ayrı bir iş ona göre yapın demiştiniz ya ben böyle anladım :| ama trellodaki card'ımız böyle olduğu için o şekilde oluyor sanırım düzeltiriz hocam :)

**Comment by seyyah** [comment]
trello'da düştüğüm uzun açıklamaya bakın

**Comment by seyyah** [comment]
bu içeriği #22'ye taşıdıktan sonra bunu kapatın.

**Comment by kcd** [comment]
tamam hocam
