### ISSUE TITLE
Anasayfa ve login girişi görsel tasarımı

### ISSUE THREAD

**Issue by kcd** [kcd/staj#24]
TODO

[Issue #22: Kullanıcılar login ekranı üzerinden giriş yapabilmeli](https://github.com/kcd/staj/issues/22)

**Comment by sedadogan** [comment]
## Anasayfa ve Login Girişi Tasarımı

Sistemimizde görsellik için twitter-bootstrap kullanıldı. Bunun sebebi, twitter-bootstrap ile web sitemizi daha hızlı oluşturabilmemizdir.Bu süreci adımlayacak olursak;

Öncelikle twitter-bootstrap dosyaları eklendi. Bu dosyalara <a href="http://twitter.github.com/bootstrap/">buradan</a> da ulaşılabilir. Bu dosyaları projemize ekleyebilmemiz için öncelikle projemizde bulunan Gemfile dosyasına assets do içerisine  aşağıdaki gibi twitter-bootstrap gemi eklenmelidir;

```
group :assets do
  gem 'twitter-bootstrap-rails'
end

```

Aşağıdaki satırı yazarak da bu gemi yüklemiş oluruz;

```
$ sudo gem install twitter-bootstrap-rails

```

yazmamız yeterlidir. Sonra komut satırında projemizin olduğu dizine gelerek;

```
$ bundle install

```

yazılmalıdır.
Projemizin bu sürecinde bazı hatarlar ile karşılaşıldı. 'bundle install' yazdığımızda bazı gem leri kurmuş olmamıza rağmen bunlar üzerinden hata aldık. Bu sorunumuz aşağıda satır ile giderildi; 

```
$ bundle install --without production

```

Gem kurma işlemi tamamlandıktan sonra bu dosyaları projemize entegre etmemiz için aşağıdaki satır yazılmalıdır.

```
$ rails g bootstrap:install

```

Bu satır ile twitter-bootstrap dosyalarını sistemimize eklemiş, entegre etmiş oluruz.
Kaynak Kodlara <a href="https://github.com/sedadogan/Twitter-Bootstrap/tree/master/%C3%B6nce/staj">buradan</a> ulaşabilirsiniz.
Ayrıntılı bilgiye <a href="http://tugdev.github.com/111/BOOTSTRAP/">buradan</a> ulaşabilirsiniz.

## Bu işlemlerin Sonucu

  **Giriş Sayfamız**

[![giriş sayfamız](http://i.imgur.com/h7wtC.png)](http://i.imgur.com/B1HNg.png)

  **Sign in Sayfamız**

[![sign in sayfamız](http://i.imgur.com/emwM9.png)](http://i.imgur.com/X3Xrj.png)

  **Staj hg**

[![sign in sayfamız](http://i.imgur.com/v3FNg.png)](http://i.imgur.com/uX9jX.png)
