### ISSUE TITLE
Heroku sayfası

### ISSUE THREAD

**Issue by begum** [kcd/staj#3]
staj.herokuapp.com web sayfasına github kcd/staj reposu deploy edilecek. @kcd

**Comment by kcd** [comment]
kcd/staj reposu, http://staj.herokuapp.com/ adresine, https://deploybutton.com/ aracılığı ile deploy edildi.

**Comment by seyyah** [comment]
index.html dosyasini silip ana sayfaya grup resmini ekleyin. 

2 Kas 2012 tarihinde 23:20 saatinde, Kamile Canan Demirel notifications@github.com şunları yazdı:

**Comment by kcd** [comment]
index.html sayfası silindi.
deploy başarılı olmasına rağmen staj.herokuapp.com sayfasındaki hata mesajı:
![](http://i.imgur.com/VldRE.png)
anasayfanın yereldeki görüntüsü eklenecek. @ntgcyslyrt

**Comment by seyyah** [comment]
bunu yerine heroku log (bugün gönderdiğim ipuçlarını kullanarak) eklemekte yarar var.

**Comment by ntgcyslyrt** [comment]
$rails s ile elde edilen görüntü
![yerel-görüntü](http://i.imgur.com/4N1N8.png)

**Comment by ntgcyslyrt** [comment]
Bu görüntüyü elde edebilmek için;
- $ rm public/index.html  
  
   komutu ile index.html dosyası silindi.
- $ rails generate controller home index      
  
   home dizini altında index.html.erb dosyası oluşturuldu daha sonra bu dosya index.html.slim dosyasına çevrildi. 
- app/views/home/index.html.slim dosyasının içine ;
  
  center
  h2 Staj Yönetim Sistemi
  hr/
  center
  kodu gömüldü.
- config/routes.rb dosyasının içeriğine ;
  
  root :to => "home#index" eklendi.

**Comment by seyyah** [comment]
No hash rocket @ntgcyslyrt,

``` ruby
# BAD
root :to => "home#index"

# GOOD
root to: "home#index"
```

**Comment by ntgcyslyrt** [comment]
pardon @seyyah hocam kodda düzeltmiştim buraya yazarken düzeltmeyi unutmuşum :)

**Comment by ntgcyslyrt** [comment]
Bu görüntüyü elde edebilmek için;

``` bash
$ rm public/index.html  
```

komutu ile index.html dosyası silindi.

``` bash
$ rails generate controller home index      
```

home dizini altında index.html.erb dosyası oluşturuldu daha sonra bu dosya index.html.slim dosyasına çevrildi.  

``` ruby
# app/views/home/index.html.slim
center
  h2 Staj Yönetim Sistemi
  hr/
```

kodu gömüldü.

``` ruby
# config/routes.rb
root to:  "home#index"
```

**Comment by seyyah** [comment]
@ntgcyslyrt yukarıda ki kommentini Markdown'laştırıyorum seninkileri koruyorum. İnceledikten sonra seninkileri silersin.

**Comment by ntgcyslyrt** [comment]
tamamdır @seyyah hocam inceledim, düzenliyorum.
