### ISSUE TITLE
Ekim ayı raporu

### ISSUE THREAD

**Issue by begum** [kcd/staj#5]
Ekim ayı raporunun, kcd/staj/wiki/aylik1 üzerinde oluşturulması @bgmtpyldz

**Comment by begum** [comment]
https://github.com/kcd/staj/wiki/aylik1 taslak olarak hazırlandı. diğer issues'lere paralel olarak eklemeler/düzeltmeler yapılacak.

**Comment by kcd** [comment]
Ekim ayının hedefleri ve sonuçları eklenecek.

**Comment by begum** [comment]
hedefler ve sonuçlar girildi.
