### ISSUE TITLE
Kişisel blogların oluşturulması

### ISSUE THREAD

**Issue by kcd** [kcd/staj#9]
Kişisel blog oluşumu @bgmtpyldz  tarafından öğrenilecek ve tüm ekip bilgilendirilecek.
Her üye kendi bloğunu oluşturacak.

Üyelerin blogları:

http://kcd.github.com/
http://bgmtpyldz.github.com/
http://sedadogan.github.com/ 
http://ntgcyslyrt.github.com/

**Comment by seyyah** [comment]
iş atamasını ilgili kişiye yapmalıydı. Bu seferliğine ben yapıyorum.

**Comment by kcd** [comment]
Düzelttim hocam.

**Comment by kcd** [comment]
http://kcd.github.com/  oluşturuldu :)

**Comment by begum** [comment]
blogların oluşturulması tamamlandı. github onayları bekleniyor.
http://bgmtpyldz.github.com/

**Comment by sedadogan** [comment]
http://sedadogan.github.com/ 
blog oluşturuldu.

**Comment by ntgcyslyrt** [comment]
http://ntgcyslyrt.github.com/ oluşturuldu :)

**Comment by seyyah** [comment]
İş gövdesinde blog adreslerinizi alt alta yazarak işi kapatabilirsiniz
